[package]
name = "alkahest-pm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
destiny-pkg.workspace = true
lazy_static.workspace = true
parking_lot.workspace = true
